### ISSUE TITLE
How to add a language ?

### ISSUE THREAD

**Issue by clojj** [atom/tree-sitter-syntax#8]
How can another language (e.g. https://github.com/tree-sitter/tree-sitter-haskell) be added ?
(assuming this repo is responsible for providing the languages, recognized by the tree-sitter option in the 1.25 beta)
Specifically, I don't understand the role of the *.cson files here..

more generally:
- Is there any tutorial on adding a language available yet ?
- is there (will there be) any API (for tree-sitter ASTs) available for atom plugin-packages ?

**Comment by clojj** [comment]
meanwhile found the answer in the PR

**Comment by maxbrunsfeld** [comment]
This repo is actually deprecated. All of the general-purpose code is now part of Atom's core. All of the language-specific code now lives in individual packages like [language-javascript](https://github.com/atom/language-javascript) ([this file](https://github.com/atom/language-javascript/blob/master/grammars/tree-sitter-javascript.cson)) and [language-python](https://github.com/atom/language-python) ([this file](https://github.com/atom/language-python/blob/master/grammars/tree-sitter-python.cson)).

To add support for a new language, you create an Atom package with a `grammars` folder. In the grammars folder, there should be a `.cson` file with the following keys:

* `id` stable identifier for the language
* `name` human-readable name for the language
* `parser` a *requireable* path to a tree-sitter language module that provides the actual parsing
* `scopes` an object where the keys are CSS selectors that select nodes in a syntax tree, and the values are classes that should be applied to those nodes for styling
* `folds` an array of objects that match syntax nodes that should be foldable and specify where the folds should start and end. For now, there aren't docs; you'll have to look at some of the existing languages as examples.

I'll write full-on documentation soon, after we develop this feature a bit more fully.
